# Generated by Django 6.1.1 on 2026-09-30 11:38

import business_page.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('client', models.CharField(max_length=120)),
                ('title', models.CharField(help_text='Headline, e.g. "Booking that runs itself".', max_length=200)),
                ('sector', models.CharField(max_length=120)),
                ('summary', models.TextField(help_text='One or two sentences for cards and meta description.')),
                ('status', models.CharField(choices=[('live', 'Live'), ('ongoing', 'Live · ongoing development'), ('in-development', 'In development'), ('completed', 'Completed'), ('support-ended', 'Support period ended')], default='completed', max_length=20)),
                ('public_url', models.URLField(blank=True)),
                ('layers', models.JSONField(blank=True, default=list)),
                ('services', models.JSONField(blank=True, default=list, help_text='Service slugs from services_data.')),
                ('stack', models.JSONField(blank=True, default=list)),
                ('scope_note', models.CharField(blank=True, help_text='What HZORTECH did vs. what belongs to the client.', max_length=300)),
                ('context', models.TextField(blank=True)),
                ('problem', models.TextField(blank=True)),
                ('system', models.TextField(blank=True)),
                ('implementation', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('architecture', models.JSONField(blank=True, default=dict)),
                ('outcomes', models.JSONField(blank=True, default=list)),
                ('cover', models.CharField(blank=True, help_text='Static path of the cover image.', max_length=200)),
                ('cover_alt', models.CharField(blank=True, max_length=200)),
                ('cover_is_illustration', models.BooleanField(default=False, help_text='Tick when the cover is illustrative rather than the real product.')),
                ('gallery', models.JSONField(blank=True, default=list, help_text='[{"src", "alt", "caption", "device": "desktop|mobile"}]')),
                ('legacy_anchor', models.CharField(blank=True, help_text='Old /projects/#anchor id kept working.', max_length=40)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=100)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'case studies',
                'ordering': ['order', 'client'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(help_text='Where the asset is used, e.g. "home.forge".', max_length=80)),
                ('model_slug', models.CharField(max_length=120)),
                ('prompt', models.TextField()),
                ('arguments', models.JSONField(default=dict)),
                ('request_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('nsfw', 'Blocked by moderation'), ('canceled', 'Canceled')], default='queued', max_length=20)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('result_url', models.URLField(blank=True, max_length=1000)),
                ('local_path', models.CharField(blank=True, max_length=300)),
                ('error', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('dek', models.CharField(help_text='Standfirst shown under the headline.', max_length=300)),
                ('topic', models.CharField(choices=[('security', 'Security'), ('devops', 'DevOps'), ('cloud', 'Cloud'), ('automation', 'Automation'), ('engineering', 'Engineering')], max_length=20)),
                ('body', models.TextField(help_text='Markdown. Fenced code blocks are syntax-highlighted.')),
                ('body_html', models.TextField(blank=True, editable=False)),
                ('toc', models.JSONField(blank=True, default=list, editable=False)),
                ('author_name', models.CharField(default='HZORTECH Engineering', max_length=120)),
                ('reading_minutes', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.CharField(default=business_page.models._token, editable=False, max_length=64, unique=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='budget',
            field=models.CharField(blank=True, choices=[('', 'Not sure yet'), ('under-5k', 'Under $5k'), ('5k-15k', '$5k – $15k'), ('15k-50k', '$15k – $50k'), ('50k-plus', '$50k +')], max_length=20),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='company',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='project_type',
            field=models.CharField(blank=True, choices=[('platform', 'A new platform or product'), ('automation', 'Automating a workflow'), ('infrastructure', 'Cloud, DevOps or infrastructure'), ('security', 'Security and hardening'), ('takeover', 'Taking over or fixing an existing system'), ('other', 'Something else')], max_length=20),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='source',
            field=models.CharField(blank=True, help_text='Page the intake was started from.', max_length=200),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='timeline',
            field=models.CharField(blank=True, choices=[('', 'Flexible'), ('asap', 'As soon as possible'), ('1-3-months', 'Within 1–3 months'), ('3-months-plus', 'In 3+ months')], max_length=20),
        ),
    ]
