"""
SEO-optimised service landing page data.
Each entry drives a dedicated page at /services/{slug}/
"""

SERVICES = {
    'devops': {
        'slug': 'devops', 'nav_label': 'DevOps & CI/CD',
        'title': 'DevOps & CI/CD Engineering in Armenia | HZORTECH Yerevan',
        'meta_desc': 'DevOps engineering and CI/CD pipeline automation in Armenia. GitHub Actions, Docker, Kubernetes, Terraform, AWS. Zero unplanned downtime. HZORTECH, Yerevan.',
        'og_title': 'DevOps & CI/CD Engineering | HZORTECH Armenia',
        'og_desc': 'CI/CD pipelines, Kubernetes orchestration, Terraform IaC, AWS cloud architecture. DevOps engineers in Yerevan, Armenia.',
        'keywords': 'DevOps Armenia, CI/CD Armenia, Kubernetes Yerevan, Docker Armenia, Terraform Armenia, GitHub Actions Armenia, infrastructure automation Armenia, cloud DevOps Yerevan, DevOps engineer Armenia',
        'label': 'DEVOPS // CI/CD ENGINEERING',
        'h1': ['AUTOMATED.', 'SCALABLE.', 'ZERO DOWNTIME.'],
        'h1_em': 'ZERO DOWNTIME.',
        'hero': 'We build production-grade CI/CD pipelines, container infrastructure, and deployment automation for engineering teams in Armenia and globally. Your code ships reliably. Your infrastructure runs without babysitting.',
        'problem_title': 'The Infrastructure Problem',
        'problem': 'Manual deployments that require a developer present. Infrastructure assembled over time with no documentation. Outages with no monitoring. Engineers spending hours on ops work instead of building product. These are engineering debt problems — and they compound.',
        'solution_title': 'Production-Grade DevOps Engineering',
        'solution': 'We design and implement the complete DevOps stack: automated CI/CD pipelines from commit to production, container orchestration with Docker and Kubernetes, infrastructure-as-code with Terraform, and monitoring systems that alert before users notice problems.',
        'stack': ['GitHub Actions', 'GitLab CI', 'Docker', 'Kubernetes', 'k3s', 'Terraform', 'Ansible', 'AWS', 'Prometheus', 'Grafana', 'Wazuh', 'Nginx'],
        'deliverables': [
            'Automated CI/CD pipeline (build → test → staging → production)',
            'Container architecture (Docker Compose or Kubernetes)',
            'Infrastructure as Code (Terraform + Ansible)',
            'Monitoring, alerting, and incident dashboards',
            'Rollback mechanisms and disaster recovery runbooks',
            'Full documentation and team knowledge transfer',
        ],
        'stats': [
            {'val': '0', 'label': 'Unplanned outages on managed systems'},
            {'val': '15×/day', 'label': 'Deploy frequency (from 2×/week)'},
            {'val': '6 min', 'label': 'Average deploy time, end-to-end'},
        ],
        'process': [
            {'step': '01', 'name': 'Infrastructure Audit', 'desc': 'Map existing deployment process, identify failure points, document what exists.'},
            {'step': '02', 'name': 'Pipeline Architecture', 'desc': 'Design CI/CD flow, branching strategy, environment topology (dev/staging/prod).'},
            {'step': '03', 'name': 'Build & Test Automation', 'desc': 'Implement automated builds, test runners, code quality gates, security scans.'},
            {'step': '04', 'name': 'Deploy & Orchestrate', 'desc': 'Container deployment, rollout strategy, health checks, automatic rollback.'},
            {'step': '05', 'name': 'Monitor & Handover', 'desc': 'Metrics, alerting, runbooks, team training. You own it after we leave.'},
        ],
        'faqs': [
            {'q': 'What DevOps services does HZORTECH provide in Armenia?', 'a': 'End-to-end DevOps engineering: CI/CD pipeline design, Docker containerisation, Kubernetes orchestration, Terraform infrastructure-as-code, AWS cloud architecture, and monitoring with Prometheus/Grafana. Based in Yerevan, Armenia, serving clients locally and internationally.'},
            {'q': 'How long does it take to build a production CI/CD pipeline?', 'a': 'A basic pipeline (build, test, deploy) takes 1-2 weeks. A full production system with staging, rollbacks, IaC, and monitoring typically takes 4-8 weeks depending on existing infrastructure.'},
            {'q': 'Do you work with existing infrastructure or only greenfield?', 'a': 'Both. We frequently modernise legacy infrastructure — migrating from manual deployments to automated pipelines, or lifting on-premise systems to cloud with minimal disruption to production.'},
            {'q': 'What cloud providers do you work with?', 'a': 'Our primary cloud platform is AWS (eu-north-1, eu-west-1, us-east-1). We work with EC2, ECS, EKS, RDS, S3, CloudWatch, and related services. We also work with bare-metal and hybrid cloud setups.'},
            {'q': 'Will our team be able to maintain the system after delivery?', 'a': 'Yes — every engagement includes operational runbooks, architecture documentation, and a knowledge transfer session. Your team operates the infrastructure independently after handover.'},
        ],
        'schema_type': 'DevOps Engineering',
        'related': ['cloud', 'cloud-migration', 'security', 'software-development'],
    },

    'software-development': {
        'slug': 'software-development', 'nav_label': 'Software Development',
        'title': 'Custom Software Development in Armenia | HZORTECH Yerevan',
        'meta_desc': 'Custom software development in Armenia. Django, Python, REST APIs, PostgreSQL, full-stack web applications built to specification. Senior engineers in Yerevan. HZORTECH.',
        'og_title': 'Custom Software Development | HZORTECH Armenia',
        'og_desc': 'Full-stack custom software: backends, web apps, REST APIs. Built to your exact spec by senior engineers in Yerevan, Armenia.',
        'keywords': 'custom software development Armenia, software developers Yerevan, Python developers Armenia, Django development Armenia, web application development Armenia, backend development Yerevan, full-stack developers Armenia, software company Armenia',
        'label': 'SOFTWARE // FULL-STACK ENGINEERING',
        'h1': ['CUSTOM.', 'PRECISE.', 'PRODUCTION-READY.'],
        'h1_em': 'PRODUCTION-READY.',
        'hero': 'We engineer custom software — backends, web applications, and APIs built to exact specification. No off-the-shelf platforms that constrain your workflow. Software that does exactly what your business requires, and is maintained by engineers who understand it end to end.',
        'problem_title': 'The Generic Platform Problem',
        'problem': 'Off-the-shelf platforms create compromises. You adapt your process to the software instead of the other way around. Data gets trapped in closed systems. Features you need don\'t exist. Features you don\'t need create complexity. Custom software eliminates all of this.',
        'solution_title': 'Built-to-Specification Engineering',
        'solution': 'We design and build software that matches your exact requirements — corporate sites, web applications, custom CRMs, internal tools, and REST API backends. Every project starts with a technical specification so you know exactly what you\'re getting before a line is written.',
        'stack': ['Python', 'Django', 'FastAPI', 'PostgreSQL', 'Redis', 'Celery', 'REST API', 'Bootstrap 5', 'JavaScript', 'Docker', 'Nginx', 'Linux'],
        'deliverables': [
            'Technical specification document before development begins',
            'Source code with full version history (GitHub/GitLab)',
            'Automated tests (unit + integration coverage)',
            'CI/CD pipeline for continuous delivery',
            'API documentation (OpenAPI / Swagger)',
            'Deployment runbook and operational documentation',
        ],
        'stats': [
            {'val': '< 200ms', 'label': 'API latency target, p95 on every endpoint'},
            {'val': '99.9%', 'label': 'Uptime SLA on managed production systems'},
            {'val': '100%', 'label': 'Spec compliance verified before handover'},
        ],
        'process': [
            {'step': '01', 'name': 'Requirements & Spec', 'desc': 'Define scope, data models, user flows, API contracts. Written spec signed off before code starts.'},
            {'step': '02', 'name': 'Architecture Design', 'desc': 'System architecture, database schema, service boundaries, security model.'},
            {'step': '03', 'name': 'Iterative Build', 'desc': 'Working software delivered in iterations. You see progress, not just the final result.'},
            {'step': '04', 'name': 'Test & Validate', 'desc': 'Automated test suite, performance benchmarks, security review, user acceptance testing.'},
            {'step': '05', 'name': 'Deploy & Handover', 'desc': 'Production deployment + runbooks + knowledge transfer. Your team takes ownership.'},
        ],
        'faqs': [
            {'q': 'What types of software does HZORTECH build?', 'a': 'Corporate websites, web applications, internal business tools, custom CRM systems, REST API backends, admin panels, automation dashboards, and SaaS platforms. Primary stack: Python/Django with PostgreSQL, delivered with Docker and CI/CD.'},
            {'q': 'Do you work on fixed-scope or ongoing projects?', 'a': 'Both. Fixed-scope projects are scoped and priced from a technical specification. Ongoing engagements work on a monthly retainer for continuous development and maintenance.'},
            {'q': 'How do you prevent scope creep?', 'a': 'Every project starts with a written technical specification defining deliverables, acceptance criteria, and what is out of scope. Changes are assessed and repriced. This protects both sides.'},
            {'q': 'Can you take over an existing codebase?', 'a': 'Yes. We audit the existing system, document what exists, then progressively refactor, modernise, or extend it based on priority. We can work with Django, Flask, Node.js, and legacy PHP codebases.'},
            {'q': 'How long does a typical project take?', 'a': 'A simple web application or API takes 4-8 weeks. A complex multi-user platform with integrations and admin panels typically takes 3-6 months. Timelines are defined in the specification phase.'},
        ],
        'schema_type': 'Software Development',
        'related': ['devops', 'api-integration', 'crm-automation', 'python'],
    },

    'crm-automation': {
        'slug': 'crm-automation', 'nav_label': 'CRM & Automation',
        'title': 'CRM & Business Process Automation in Armenia | HZORTECH Yerevan',
        'meta_desc': 'CRM setup and business process automation in Armenia. HubSpot, custom CRM, n8n workflow automation, API integrations. Eliminate manual work. HZORTECH, Yerevan.',
        'og_title': 'CRM & Business Process Automation | HZORTECH Armenia',
        'og_desc': 'Automate your sales pipeline, workflows, and business processes. HubSpot, n8n, custom CRM. Based in Yerevan, Armenia.',
        'keywords': 'CRM automation Armenia, business automation Yerevan, HubSpot Armenia, workflow automation Armenia, process automation Yerevan, n8n Armenia, automation company Armenia, business software Armenia, CRM setup Yerevan',
        'label': 'CRM // PROCESS AUTOMATION',
        'h1': ['AUTOMATE.', 'ELIMINATE.', 'SCALE.'],
        'h1_em': 'ELIMINATE.',
        'hero': 'We automate the workflows that eat your team\'s time — sales pipelines, client onboarding, follow-ups, reporting, data entry, and cross-system integrations. Based in Yerevan, Armenia, we build automation systems that run without supervision.',
        'problem_title': 'The Manual Workflow Problem',
        'problem': 'Repetitive tasks that should run automatically. Sales leads falling through gaps because no one followed up. Data living in three systems that don\'t talk to each other. Reports that take two hours to generate weekly by hand. These are solvable engineering problems.',
        'solution_title': 'Trigger-Based Process Engineering',
        'solution': 'We map your current workflows, identify what should be automatic, and build trigger-based automation systems. CRM configuration, webhook pipelines, n8n workflows, and API integrations that connect your tools and remove humans from repetitive loops.',
        'stack': ['HubSpot', 'n8n', 'Zapier', 'Make (Integromat)', 'Python', 'REST APIs', 'Webhooks', 'PostgreSQL', 'Airtable', 'Notion API', 'Gmail API', 'Slack API'],
        'deliverables': [
            'Workflow audit and automation opportunity map',
            'CRM configuration and pipeline setup',
            'Trigger-based automation (webhooks, schedules, events)',
            'System integrations (CRM ↔ email ↔ calendar ↔ tools)',
            'Automated reporting and analytics',
            'Team training and documentation',
        ],
        'stats': [
            {'val': '10+ hrs/wk', 'label': 'Typical manual work eliminated per engagement'},
            {'val': '100%', 'label': 'Event-driven — no polling, no missed triggers'},
            {'val': '48h', 'label': 'Maximum response time on all automated alerts'},
        ],
        'process': [
            {'step': '01', 'name': 'Workflow Audit', 'desc': 'Map all manual processes, identify automation targets, estimate time savings.'},
            {'step': '02', 'name': 'CRM Setup', 'desc': 'Configure pipeline stages, custom fields, automation rules, and user roles.'},
            {'step': '03', 'name': 'Integration Build', 'desc': 'Connect tools via API, webhooks, and automation platforms.'},
            {'step': '04', 'name': 'Test & Tune', 'desc': 'End-to-end testing of automation flows, edge case handling, error notifications.'},
            {'step': '05', 'name': 'Train & Handover', 'desc': 'Team training, documentation, and 30-day monitoring period.'},
        ],
        'faqs': [
            {'q': 'What CRM platforms does HZORTECH work with in Armenia?', 'a': 'Primarily HubSpot (setup, configuration, custom integrations, automation). We also build fully custom CRM systems for businesses that need something off-the-shelf platforms cannot provide. For workflows: n8n, Make (Integromat), and custom Python-based systems.'},
            {'q': 'What business processes can be automated?', 'a': 'Lead capture and routing, automated follow-up sequences, client onboarding, invoice generation, appointment scheduling, reporting, data sync between tools, Slack/email notifications, and more. If a human does the same task repeatedly, it can likely be automated.'},
            {'q': 'How much time can automation actually save?', 'a': 'Teams with heavy manual follow-ups and data entry typically recover 10-20 hours per week. Sales teams see higher conversion rates from consistent automated follow-up. ROI is usually clear within 60-90 days.'},
            {'q': 'We already have a CRM — can you automate within it?', 'a': 'Yes. We frequently add automation layers to existing setups, fix broken workflows, build integrations with other tools, and configure advanced features not currently being used.'},
        ],
        'schema_type': 'Business Process Automation',
        'related': ['software-development', 'api-integration', 'devops', 'smart-home-automation'],
    },

    'smart-home-automation': {
        'slug': 'smart-home-automation', 'nav_label': 'Smart Home & IoT',
        'title': 'Smart Home & IoT Automation in Armenia | HZORTECH Yerevan',
        'meta_desc': 'Smart home automation and IoT system development in Armenia. Device integration, real-time dashboards, automation rules, cloud connectivity. HZORTECH, Yerevan.',
        'og_title': 'Smart Home & IoT Automation | HZORTECH Armenia',
        'og_desc': 'Smart home automation systems, IoT device integration, control dashboards. Engineering from Yerevan, Armenia.',
        'keywords': 'smart home Armenia, home automation Armenia, IoT Armenia, smart home Yerevan, home automation system Armenia, IoT integration Armenia, building automation Armenia, smart building Armenia, home automation company Armenia',
        'label': 'SMART HOME // IoT ENGINEERING',
        'h1': ['CONNECTED.', 'INTELLIGENT.', 'AUTOMATED.'],
        'h1_em': 'INTELLIGENT.',
        'hero': 'We design and build smart home and IoT automation systems — from device integration and real-time control dashboards to cloud-connected platforms and rule-based automation engines. Hardware and software, engineered together from Yerevan, Armenia.',
        'problem_title': 'The Disconnected Systems Problem',
        'problem': 'Smart devices requiring five different apps. Automations that only work when the internet is up. Systems that can\'t communicate with each other. Proprietary platforms that lock you in. Real smart home engineering solves these at the infrastructure level.',
        'solution_title': 'Full-Stack IoT Architecture',
        'solution': 'We connect hardware devices (sensors, controllers, HVAC, lighting, security) to a unified software platform. Real-time dashboards, mobile control, rule-based automations, and cloud connectivity — built as a coherent system, not a collection of apps.',
        'stack': ['Python', 'MQTT', 'Home Assistant', 'Node-RED', 'REST APIs', 'WebSockets', 'Docker', 'Raspberry Pi', 'ESP32/ESP8266', 'AWS IoT Core', 'PostgreSQL', 'Grafana'],
        'deliverables': [
            'Device integration architecture (protocol, wiring, commissioning)',
            'Unified control dashboard (web + mobile)',
            'Automation rule engine (schedules, triggers, conditions)',
            'Cloud connectivity and remote monitoring',
            'Alert and notification system',
            'Full system documentation and user guide',
        ],
        'stats': [
            {'val': '< 50ms', 'label': 'Real-time dashboard response target'},
            {'val': 'Local-first', 'label': 'Automations run without cloud dependency'},
            {'val': '24/7', 'label': 'Uptime target for core automation systems'},
        ],
        'process': [
            {'step': '01', 'name': 'Site Assessment', 'desc': 'Audit existing systems, map device ecosystem, define automation goals.'},
            {'step': '02', 'name': 'System Design', 'desc': 'Protocol selection, network architecture, hub placement, software platform.'},
            {'step': '03', 'name': 'Hardware Integration', 'desc': 'Device commissioning, sensor placement, controller wiring, testing.'},
            {'step': '04', 'name': 'Software Build', 'desc': 'Dashboard development, automation rules, notifications, mobile interface.'},
            {'step': '05', 'name': 'Deploy & Document', 'desc': 'Full system testing, user training, emergency override procedures, documentation.'},
        ],
        'faqs': [
            {'q': 'What smart home systems does HZORTECH work with in Armenia?', 'a': 'Protocol-agnostic platforms (Home Assistant, Node-RED) integrating Z-Wave, Zigbee, MQTT, and WiFi-based devices. We also build custom IoT solutions using ESP32/ESP8266 and Raspberry Pi, with cloud connectivity via AWS IoT Core.'},
            {'q': 'Can you retrofit an existing home or only new builds?', 'a': 'Both. We retrofit existing homes and commercial buildings — adding smart switches, sensors, and controllers to existing infrastructure. We also design from scratch for new construction.'},
            {'q': 'Will the system work if the internet goes down?', 'a': 'Yes — this is a core design requirement. Automations (lights, HVAC, locks) run locally and do not require internet connectivity. Remote access and cloud features are layered on top, not load-bearing.'},
            {'q': 'Do you offer commercial building automation?', 'a': 'Yes. We work on commercial buildings, server rooms, industrial facilities, and infrastructure monitoring. For industrial contexts, we also work with PLCs, SCADA-adjacent systems, and custom sensor networks.'},
        ],
        'schema_type': 'IoT and Smart Home Automation',
        'related': ['software-development', 'crm-automation', 'cloud', 'hpc-linux'],
    },

    'cloud': {
        'slug': 'cloud', 'nav_label': 'Cloud Infrastructure',
        'title': 'Cloud Infrastructure Engineering in Armenia | AWS | HZORTECH Yerevan',
        'meta_desc': 'Cloud infrastructure engineering on AWS in Armenia. EC2, ECS, EKS, RDS, S3, VPC, Terraform IaC. Designed, deployed, documented. HZORTECH, Yerevan.',
        'og_title': 'Cloud Infrastructure Engineering | AWS | HZORTECH Armenia',
        'og_desc': 'AWS cloud architecture, Terraform IaC, container platforms. HZORTECH engineers in Yerevan, Armenia.',
        'keywords': 'cloud infrastructure Armenia, AWS Armenia, cloud engineering Yerevan, AWS cloud Armenia, cloud architecture Armenia, cloud engineers Armenia, cloud computing Armenia, AWS EC2 Armenia, cloud services Yerevan',
        'label': 'CLOUD // INFRASTRUCTURE ENGINEERING',
        'h1': ['ELASTIC.', 'SECURE.', 'ALWAYS ON.'],
        'h1_em': 'ALWAYS ON.',
        'hero': 'We design, build, and operate cloud infrastructure on AWS — from single-server deployments to multi-region containerised platforms. Every system is documented, monitored, and handed over with full operational runbooks.',
        'problem_title': 'The Infrastructure Reliability Problem',
        'problem': 'Cloud is easy to set up badly. Servers without backups. Security groups that allow everything. No monitoring. No disaster recovery. Infrastructure assembled by hand with no record of what was configured or why. This works until it fails — with no way to recover quickly.',
        'solution_title': 'Engineered Cloud Architecture',
        'solution': 'We design infrastructure using security-first, reliability-first principles. Every component is defined in Terraform code, every change is tracked, every system has monitoring and alerting. Infrastructure your team can operate and that has documented recovery procedures.',
        'stack': ['AWS EC2', 'AWS ECS/EKS', 'AWS RDS', 'AWS S3', 'AWS VPC', 'AWS IAM', 'AWS CloudWatch', 'Terraform', 'Docker', 'Kubernetes', 'Nginx', 'Cloudflare'],
        'deliverables': [
            'Cloud architecture diagram and design document',
            'Terraform IaC (reproducible, versioned infrastructure)',
            'Network and security configuration (VPC, security groups, IAM)',
            'Database setup with backups and point-in-time recovery',
            'Monitoring, alerting, and logging (CloudWatch / Grafana)',
            'Disaster recovery runbook and operational documentation',
        ],
        'stats': [
            {'val': '99.99%', 'label': 'Uptime target on properly architected systems'},
            {'val': '100% IaC', 'label': 'All infrastructure defined in Terraform'},
            {'val': '< 1h RTO', 'label': 'Recovery time on documented runbooks'},
        ],
        'process': [
            {'step': '01', 'name': 'Architecture Design', 'desc': 'Requirements, sizing, region selection, network topology, security model.'},
            {'step': '02', 'name': 'Infrastructure as Code', 'desc': 'All resources defined in Terraform — reproducible, versioned, auditable.'},
            {'step': '03', 'name': 'Security Hardening', 'desc': 'IAM least-privilege, security groups, encryption at rest and in transit, VPC isolation.'},
            {'step': '04', 'name': 'Monitoring & Alerting', 'desc': 'CloudWatch dashboards, alert thresholds, Slack/PagerDuty integration.'},
            {'step': '05', 'name': 'Handover & Docs', 'desc': 'Architecture docs, runbooks, team training, 30-day monitoring period.'},
        ],
        'faqs': [
            {'q': 'What cloud platform does HZORTECH use?', 'a': 'Our primary platform is Amazon Web Services (AWS), using regions in Europe (eu-north-1 Stockholm, eu-west-1 Ireland) and US East. We work with EC2, ECS, EKS, RDS, S3, CloudFront, Route53, IAM, and more.'},
            {'q': 'Do you work with clouds other than AWS?', 'a': 'We specialise in AWS. We also work with bare-metal Linux servers (VPS or dedicated) and hybrid cloud setups where some workloads remain on-premise.'},
            {'q': 'How do you ensure cloud infrastructure is secure?', 'a': 'AWS security best practices: least-privilege IAM policies, private subnets for databases and application servers, security group rules limited to required traffic, encryption at rest and in transit, CloudTrail audit logging, and regular security reviews.'},
            {'q': 'What is infrastructure-as-code and why does it matter?', 'a': 'All cloud resources (servers, databases, networks, security rules) defined in Terraform configuration files stored in version control. Your infrastructure is reproducible, changes are tracked and reviewable, and nothing is hand-crafted that could get lost.'},
        ],
        'schema_type': 'Cloud Infrastructure Engineering',
        'related': ['devops', 'cloud-migration', 'security', 'hpc-linux'],
    },

    'python': {
        'slug': 'python', 'nav_label': 'Python Development',
        'title': 'Python Development Services in Armenia | HZORTECH Yerevan',
        'meta_desc': 'Python development in Armenia. Django, FastAPI, data pipelines, automation scripts, HPC workflows, REST APIs. Senior Python engineers in Yerevan. HZORTECH.',
        'og_title': 'Python Development | HZORTECH Armenia',
        'og_desc': 'Django, FastAPI, data pipelines, automation, HPC workflows. Senior Python engineers in Yerevan, Armenia.',
        'keywords': 'Python developers Armenia, Python development Yerevan, Django Armenia, FastAPI Armenia, Python engineers Armenia, Python automation Armenia, Django developer Yerevan, Python backend Armenia, hire Python developers Armenia',
        'label': 'PYTHON // BACKEND ENGINEERING',
        'h1': ['PYTHONIC.', 'PERFORMANT.', 'PRODUCTION-GRADE.'],
        'h1_em': 'PERFORMANT.',
        'hero': 'We build Python-based systems — Django and FastAPI backends, data pipelines, automation frameworks, scientific computing workflows, and CLI tools. Clean, tested, type-annotated, documented code that runs at production scale.',
        'problem_title': 'The Python Engineering Gap',
        'problem': 'Python code that works on a laptop and fails at scale. Scripts that grew into systems with no architecture. Django apps with N+1 query problems. Automation scripts that break silently with no logging. The language is not the problem — engineering discipline is.',
        'solution_title': 'Engineered Python Systems',
        'solution': 'We build Python systems with production engineering discipline: proper architecture, database query optimisation, async where it helps, test coverage, CI/CD, and operational monitoring. From small automation scripts to high-throughput APIs and HPC scheduling systems.',
        'stack': ['Python 3.x', 'Django', 'FastAPI', 'Celery', 'SQLAlchemy', 'PostgreSQL', 'Redis', 'Pydantic', 'pytest', 'mypy', 'Docker', 'AWS Lambda', 'Pandas', 'NumPy'],
        'deliverables': [
            'Python application with documented architecture',
            'Test suite (unit + integration, coverage report)',
            'Type annotations — mypy clean',
            'Docker container or deployment package',
            'API documentation (OpenAPI for web APIs)',
            'Performance benchmarks on compute-intensive systems',
        ],
        'stats': [
            {'val': '< 200ms', 'label': 'API response time target, p95'},
            {'val': 'Typed', 'label': 'Type-annotated, mypy-clean code standard'},
            {'val': 'Tested', 'label': 'Unit + integration coverage on all deliverables'},
        ],
        'process': [
            {'step': '01', 'name': 'Requirements & Architecture', 'desc': 'Data models, API contracts, async vs sync, queue strategy.'},
            {'step': '02', 'name': 'Core Implementation', 'desc': 'Test-driven development, type annotations, database schema, business logic.'},
            {'step': '03', 'name': 'Integration & Performance', 'desc': 'Database optimisation, caching strategy, async tasks, load testing.'},
            {'step': '04', 'name': 'CI/CD & Deploy', 'desc': 'Automated tests, Docker build, deployment pipeline, staging environment.'},
            {'step': '05', 'name': 'Documentation & Handover', 'desc': 'Architecture docs, API reference, operational guide, code review session.'},
        ],
        'faqs': [
            {'q': 'What Python frameworks does HZORTECH specialise in?', 'a': 'Primary frameworks: Django (full-stack web apps, admin interfaces, complex data models) and FastAPI (high-performance REST APIs, async services). We also build data pipelines with Pandas/NumPy, background task systems with Celery, and HPC workflows for scientific computing.'},
            {'q': 'Can you optimise an existing Python application?', 'a': 'Yes. We audit and optimise existing Django or Flask applications — identifying N+1 queries, adding caching layers, profiling slow endpoints, and refactoring monolithic code into maintainable modules.'},
            {'q': 'Do you write tests and documentation as part of delivery?', 'a': 'Yes — non-negotiable. Every Python system includes a pytest test suite, type annotations, and at minimum an architecture document explaining how the system works and how to operate it.'},
            {'q': 'Can Python handle our high-throughput requirements?', 'a': 'Yes. With the right architecture — async I/O (FastAPI + asyncio), connection pooling, Redis caching, Celery for background tasks, and query optimisation — Python systems handle thousands of requests per second.'},
        ],
        'schema_type': 'Python Software Development',
        'related': ['software-development', 'api-integration', 'devops', 'hpc-linux'],
    },

    'api-integration': {
        'slug': 'api-integration', 'nav_label': 'API Integration',
        'title': 'API & System Integration Services in Armenia | HZORTECH Yerevan',
        'meta_desc': 'API and system integration in Armenia. REST APIs, webhooks, legacy modernisation, third-party integrations. Senior engineers in Yerevan. HZORTECH.',
        'og_title': 'API & System Integration | HZORTECH Armenia',
        'og_desc': 'REST APIs, webhooks, legacy modernisation, system-to-system integrations. Engineers in Yerevan, Armenia.',
        'keywords': 'API integration Armenia, system integration Yerevan, REST API development Armenia, webhook integration Armenia, API developers Armenia, system integration Armenia, software integration Yerevan',
        'label': 'API // SYSTEM INTEGRATION',
        'h1': ['CONNECTED.', 'DOCUMENTED.', 'RELIABLE.'],
        'h1_em': 'DOCUMENTED.',
        'hero': 'We connect systems that were never designed to talk to each other — legacy platforms, third-party APIs, internal tools, and external services. REST APIs, webhooks, message queues, and event-driven integrations that are reliable, documented, and maintainable.',
        'problem_title': 'The Disconnected Systems Problem',
        'problem': 'Your CRM doesn\'t know what your support system knows. Your e-commerce platform doesn\'t sync with accounting. Manual exports someone runs on Friday afternoon. Systems bought independently that now need to work as one.',
        'solution_title': 'Integration Engineering That Sticks',
        'solution': 'We design integration architecture that connects your systems reliably — REST APIs with proper error handling, webhook processors that don\'t lose events, data transformation layers, and monitoring that tells you when something stops working.',
        'stack': ['REST APIs', 'GraphQL', 'Webhooks', 'OAuth2/JWT', 'OpenAPI/Swagger', 'Python', 'Celery', 'Redis', 'PostgreSQL', 'n8n', 'Postman', 'Docker'],
        'deliverables': [
            'Integration architecture document',
            'REST API implementation with OpenAPI documentation',
            'Webhook processors with retry logic and dead-letter queues',
            'Data transformation and mapping layer',
            'Error handling, logging, and alerting',
            'Integration test suite',
        ],
        'stats': [
            {'val': '99.9%', 'label': 'Webhook delivery reliability target'},
            {'val': 'OpenAPI', 'label': 'All APIs documented before delivery'},
            {'val': 'Retry logic', 'label': 'Exponential backoff on all async ops'},
        ],
        'process': [
            {'step': '01', 'name': 'Systems Audit', 'desc': 'Document all systems, available APIs, data models, auth mechanisms.'},
            {'step': '02', 'name': 'Integration Design', 'desc': 'Data flow diagrams, error handling strategy, retry logic, monitoring points.'},
            {'step': '03', 'name': 'Build & Test', 'desc': 'Implementation with real API endpoints, integration tests, mock servers.'},
            {'step': '04', 'name': 'Deploy & Monitor', 'desc': 'Production deployment, logging, alerting on failures, dead-letter queues.'},
            {'step': '05', 'name': 'Document & Handover', 'desc': 'Integration maps, API reference, troubleshooting guide, runbook.'},
        ],
        'faqs': [
            {'q': 'What types of integrations does HZORTECH build?', 'a': 'REST API integrations, webhook processors, event-driven message systems, CRM integrations (HubSpot, Salesforce), payment gateways, communication APIs (Twilio, SendGrid), legacy system modernisation, and custom connector platforms.'},
            {'q': 'What happens if a third-party API goes down?', 'a': 'We design for failure: retry logic with exponential backoff, dead-letter queues for unprocessable events, circuit breakers for failing upstream services, and alerting when error rates spike.'},
            {'q': 'Can you integrate with systems that have no API?', 'a': 'Yes. For legacy systems without APIs: database-level connectors, file-based exchange (CSV/XML/JSON), or scoping a modernisation project to add proper APIs.'},
        ],
        'schema_type': 'System Integration',
        'related': ['software-development', 'crm-automation', 'python', 'devops'],
    },

    'security': {
        'slug': 'security', 'nav_label': 'Cybersecurity',
        'title': 'Cybersecurity & DevSecOps in Armenia | SIEM | HZORTECH Yerevan',
        'meta_desc': 'Cybersecurity engineering and DevSecOps in Armenia. Wazuh SIEM, endpoint hardening, CIS Benchmarks, blue team operations. HZORTECH, Yerevan.',
        'og_title': 'Cybersecurity & DevSecOps | SIEM | HZORTECH Armenia',
        'og_desc': 'SIEM implementation, endpoint hardening, CIS Benchmarks, blue team ops. Cybersecurity engineers in Yerevan, Armenia.',
        'keywords': 'cybersecurity Armenia, DevSecOps Armenia, SIEM Armenia, Wazuh Armenia, endpoint hardening Armenia, security monitoring Yerevan, blue team Armenia, information security Armenia, cybersecurity company Armenia, CIS Benchmarks Armenia',
        'label': 'SECURITY // DevSecOps',
        'h1': ['VISIBLE.', 'HARDENED.', 'DEFENDED.'],
        'h1_em': 'DEFENDED.',
        'hero': 'We implement security monitoring, endpoint hardening, and DevSecOps practices that make threats visible before they become incidents. Based in Yerevan, Armenia — serving organisations that take infrastructure security seriously.',
        'problem_title': 'The Invisible Threat Problem',
        'problem': 'Most systems are breached before anyone notices. No SIEM means no visibility. Default OS configurations have known vulnerabilities. Servers exposed to the internet without hardening. Security treated as an afterthought gets treated by attackers accordingly.',
        'solution_title': 'Defence in Depth Engineering',
        'solution': 'We implement layered security: SIEM for centralised visibility, endpoint hardening against CIS Benchmarks, network segmentation, intrusion detection, log aggregation, and automated alerting. Every system we build starts secure, not gets secured later.',
        'stack': ['Wazuh SIEM', 'Splunk', 'ELK Stack', 'CIS Benchmarks', 'OWASP', 'Nessus', 'OpenVAS', 'iptables/nftables', 'fail2ban', 'auditd', 'SELinux', 'AWS Security Hub'],
        'deliverables': [
            'Security architecture review and gap analysis',
            'SIEM deployment and rule configuration (Wazuh or Splunk)',
            'Endpoint hardening (CIS Level 1/2)',
            'Network security configuration (firewall rules, segmentation)',
            'Incident response runbook',
            'Compliance mapping (ISO 27001, PCI-DSS, GDPR, CBA)',
        ],
        'stats': [
            {'val': '-78%', 'label': 'Mean detection time after SIEM deployment'},
            {'val': 'CIS L2', 'label': 'Benchmark compliance on all hardened endpoints'},
            {'val': '< 15 min', 'label': 'Alert-to-triage with automated correlation rules'},
        ],
        'process': [
            {'step': '01', 'name': 'Security Audit', 'desc': 'Asset inventory, vulnerability scan, current posture assessment.'},
            {'step': '02', 'name': 'Architecture Design', 'desc': 'SIEM topology, alert taxonomy, log sources, retention policy.'},
            {'step': '03', 'name': 'SIEM Deployment', 'desc': 'Install agents, ingest log sources, build correlation rules.'},
            {'step': '04', 'name': 'Endpoint Hardening', 'desc': 'CIS Benchmark implementation, remove unnecessary services, tighten access controls.'},
            {'step': '05', 'name': 'Tune & Handover', 'desc': 'False positive reduction, alert playbooks, SOC runbooks, team training.'},
        ],
        'faqs': [
            {'q': 'What SIEM platform does HZORTECH implement?', 'a': 'Primarily Wazuh — open-source SIEM for log analysis, intrusion detection, file integrity monitoring, and compliance reporting. For larger organisations: Splunk or Elastic SIEM. Choice depends on scale, budget, and team capability.'},
            {'q': 'What is CIS Benchmark hardening?', 'a': 'CIS Benchmarks are industry-standard configuration baselines for Linux, Windows, cloud services, and applications. Implementing them removes known attack vectors — default credentials, open services, weak permissions. We implement Level 1 and Level 2 hardening.'},
            {'q': 'Do you provide ongoing monitoring or just initial setup?', 'a': 'Both. Initial engagements set up the infrastructure (SIEM, hardening, alerting). Ongoing retainers provide monthly reviews, alert tuning, vulnerability management, and incident response support.'},
            {'q': 'Can you help with regulatory compliance?', 'a': 'Yes. We work with Armenian CBA requirements, GDPR, ISO 27001, and PCI-DSS. We map security controls to compliance frameworks and implement the required technical controls.'},
        ],
        'schema_type': 'Cybersecurity',
        'related': ['devops', 'cloud', 'software-development', 'hpc-linux'],
    },

    'cloud-migration': {
        'slug': 'cloud-migration', 'nav_label': 'Cloud Migration',
        'title': 'Cloud Migration Services in Armenia | On-Premise to AWS | HZORTECH',
        'meta_desc': 'Cloud migration services in Armenia. On-premise to AWS with zero data loss. Blue/green deployments, database migration. HZORTECH, Yerevan.',
        'og_title': 'Cloud Migration | On-Premise to AWS | HZORTECH Armenia',
        'og_desc': 'On-premise to cloud migration, zero downtime and zero data loss. AWS, blue/green. HZORTECH engineers in Yerevan, Armenia.',
        'keywords': 'cloud migration Armenia, AWS migration Yerevan, on-premise to cloud Armenia, cloud migration service Armenia, server migration Armenia, cloud transition Armenia, AWS Armenia',
        'label': 'CLOUD MIGRATION // ZERO DOWNTIME',
        'h1': ['LIFT.', 'MIGRATE.', 'MODERNISE.'],
        'h1_em': 'MODERNISE.',
        'hero': 'We migrate on-premise infrastructure and legacy systems to cloud with zero data loss and minimal downtime. Server migrations, database migrations, full application stack migrations — with documented rollback plans at every stage.',
        'problem_title': 'The Migration Risk Problem',
        'problem': 'Cloud migrations fail when they\'re rushed. Data gets lost. Configurations get missed. Downtime windows run over. Applications that worked on-premise break in cloud networking. The risk is real — and it\'s mitigated by engineering discipline, not optimism.',
        'solution_title': 'Phased, Risk-Managed Migration',
        'solution': 'We execute migrations in phases with documented rollback procedures at each stage. Shadow environments run in parallel. Data integrity is verified before cutover. Blue/green deployment means zero-downtime for users. Post-migration monitoring confirms everything runs correctly.',
        'stack': ['AWS EC2', 'AWS RDS', 'AWS S3', 'AWS VPC', 'Terraform', 'Docker', 'rsync', 'pg_dump/pg_restore', 'MySQL tools', 'Nginx', 'Certbot', 'Cloudflare'],
        'deliverables': [
            'Migration plan with timeline, risk register, rollback procedures',
            'Pre-migration infrastructure audit',
            'Shadow environment setup and testing',
            'Data migration with integrity verification',
            'DNS cutover plan (zero-downtime)',
            '30-day post-migration monitoring and support',
        ],
        'stats': [
            {'val': '0', 'label': 'Data loss on all completed migrations'},
            {'val': 'Blue/green', 'label': 'Zero-downtime cutover strategy'},
            {'val': '30 days', 'label': 'Post-migration monitoring included'},
        ],
        'process': [
            {'step': '01', 'name': 'Migration Audit', 'desc': 'Inventory all systems, document dependencies, identify migration blockers.'},
            {'step': '02', 'name': 'Target Architecture', 'desc': 'Design cloud architecture, size instances, plan data migration strategy.'},
            {'step': '03', 'name': 'Shadow Environment', 'desc': 'Build target, migrate data copy, test all application functions.'},
            {'step': '04', 'name': 'Cutover', 'desc': 'Final data sync, DNS cutover, monitoring, confirmation of all services.'},
            {'step': '05', 'name': 'Post-Migration', 'desc': '30-day monitoring, performance tuning, cost optimisation, documentation.'},
        ],
        'faqs': [
            {'q': 'What does a cloud migration engagement include?', 'a': 'Pre-migration audit, target cloud architecture design (Terraform IaC), shadow environment build and testing, data migration with integrity verification, zero-downtime DNS cutover, and 30-day post-migration monitoring. Rollback procedures documented for every stage.'},
            {'q': 'How do you achieve zero downtime during migration?', 'a': 'Blue/green deployment strategy: new environment runs in parallel with production, data syncs in near-real-time, DNS cutover happens in seconds once the new environment is verified. Traffic rolls back within minutes if any issue is detected.'},
            {'q': 'What if something breaks after migration?', 'a': 'Every migration has documented rollback. The old environment remains running for 7-14 days post-cutover and can be switched back to within minutes. All configurations are documented.'},
            {'q': 'Can you migrate databases without data loss?', 'a': 'Yes. We use database-specific tools (pg_dump/restore for PostgreSQL, AWS DMS for complex migrations) with checksums and row counts verified before and after. For live databases, logical replication syncs changes continuously during migration.'},
        ],
        'schema_type': 'Cloud Migration',
        'related': ['cloud', 'devops', 'security', 'software-development'],
    },

    'hpc-linux': {
        'slug': 'hpc-linux', 'nav_label': 'HPC & Linux',
        'title': 'HPC & Linux Systems Engineering in Armenia | HZORTECH Yerevan',
        'meta_desc': 'HPC systems, Linux infrastructure, and scientific computing in Armenia. Python HPC workflows, job scheduling, AWS Batch, cluster management. HZORTECH Yerevan.',
        'og_title': 'HPC & Linux Systems Engineering | HZORTECH Armenia',
        'og_desc': 'High-performance computing, Linux infrastructure, job scheduling, AWS Batch. Engineers in Yerevan, Armenia.',
        'keywords': 'HPC Armenia, Linux infrastructure Armenia, high performance computing Yerevan, scientific computing Armenia, Linux systems Yerevan, HPC engineering Armenia, Linux engineer Armenia, cluster management Armenia, AWS Batch Armenia',
        'label': 'HPC // LINUX SYSTEMS ENGINEERING',
        'h1': ['COMPUTE.', 'SCHEDULE.', 'SCALE.'],
        'h1_em': 'SCALE.',
        'hero': 'We engineer high-performance computing systems, Linux infrastructure, and scientific workflow automation. From bare-metal cluster management to cloud-based HPC on AWS Batch — compute infrastructure that processes workloads at scale without manual intervention.',
        'problem_title': 'The HPC Engineering Problem',
        'problem': 'HPC workloads that run locally but can\'t scale. Job schedulers configured incorrectly. Scientists writing infrastructure code instead of running experiments. Resources sitting idle half the time. No monitoring, no alerting, no automation.',
        'solution_title': 'Production HPC Architecture',
        'solution': 'We build HPC systems that scale: Python-based workflow managers, automated job dispatching, cloud burst with AWS Batch, cluster monitoring, and result collection pipelines. Science runs. Engineers don\'t babysit jobs.',
        'stack': ['Python', 'Slurm', 'PBS/Torque', 'AWS Batch', 'AWS EC2 HPC', 'Docker', 'Singularity', 'MPI', 'NumPy', 'SciPy', 'Linux (RHEL/Ubuntu)', 'NFS/Lustre', 'Ansible'],
        'deliverables': [
            'HPC architecture design and sizing',
            'Job scheduler configuration (Slurm, PBS, or AWS Batch)',
            'Python workflow automation framework',
            'Monitoring and job status dashboard',
            'Storage configuration (NFS, Lustre, or S3)',
            'System administration documentation and runbooks',
        ],
        'stats': [
            {'val': '1,000+', 'label': 'Simulation jobs/month automated on production HPC'},
            {'val': '-60%', 'label': 'Compute cost reduction via scheduling optimisation'},
            {'val': '24/7', 'label': 'Automated monitoring on all managed systems'},
        ],
        'process': [
            {'step': '01', 'name': 'Workload Analysis', 'desc': 'Characterise compute requirements, parallelisation potential, I/O patterns.'},
            {'step': '02', 'name': 'Architecture Design', 'desc': 'Cluster topology, scheduler selection, storage architecture, network.'},
            {'step': '03', 'name': 'System Build', 'desc': 'OS installation, scheduler deployment, job templates, Python workflow scripts.'},
            {'step': '04', 'name': 'Validation & Benchmark', 'desc': 'Run reference workloads, verify results, measure throughput and efficiency.'},
            {'step': '05', 'name': 'Operations Handover', 'desc': 'Admin documentation, user guides, monitoring setup, team training.'},
        ],
        'faqs': [
            {'q': 'What HPC environments does HZORTECH work with?', 'a': 'Slurm-based clusters, PBS/Torque environments, AWS Batch for cloud HPC, and custom Python job orchestration. We have experience with quantum simulation, molecular dynamics, and large-scale data processing.'},
            {'q': 'Can you migrate HPC workloads to AWS cloud?', 'a': 'Yes. Direct experience migrating from on-premise to AWS using EC2 HPC instances (C5n, Hpc6a), AWS Batch for orchestration, S3 for storage, and EFA for low-latency MPI communication.'},
            {'q': 'Do you manage Linux servers as well?', 'a': 'Yes. Linux sysadmin is core to our practice — RHEL/CentOS, Ubuntu, Debian. Server hardening, user management, network configuration, storage, and performance tuning. Bare metal, VMs, and containers.'},
            {'q': 'Can you automate scientific workflows in Python?', 'a': 'Yes. We build Python workflow frameworks handling job submission, dependency management, result collection, error handling, and reporting. Scientists define what to compute — the framework handles when and how.'},
        ],
        'schema_type': 'High-Performance Computing Engineering',
        'related': ['cloud', 'python', 'devops', 'software-development'],
    },
}

SERVICE_ORDER = [
    'software-development', 'devops', 'crm-automation', 'smart-home-automation',
    'cloud', 'python', 'api-integration', 'security', 'cloud-migration', 'hpc-linux',
]
